import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Fondamento } from "next/font/google";
import { Amaranth } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fondamento = Fondamento({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const amaranth = Amaranth({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-amaranth",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${amaranth.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
